// @vitest-environment node
import { readFileSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

let db: PGlite;
const user = "11111111-1111-4111-a111-111111111111";
const other = "22222222-2222-4222-a222-222222222222";
const device = "33333333-3333-4333-a333-333333333333";
const state = { titulo: "Culto", data_escala: "2026-10-04", status: "PUBLICADA", observacoes: null,
  funcoes_usuarios: [{ usuarioId: user, funcao: "guitarra" }], tonalidades_musicas: [], usuario_ids: [user], musica_ids: [] };
async function save(mode: string, id: number | null, before: unknown, after: unknown, notices: unknown) {
  return db.query<{ id: number }>("select wf_save_schedule($1,$2,$3,$4,$5) as id", [mode, id, JSON.stringify(before), JSON.stringify(after), JSON.stringify(notices)]);
}
const notice = { usuario_id: user, tipo: "nova", titulo: "Nova escala", mensagem: "Guitarra" };
beforeAll(async () => {
  db = new PGlite();
  await db.exec(`create role anon; create role authenticated; create role service_role;
    create table profiles(id uuid primary key);
    create table musicas(id bigint primary key);
    create table escalas(id bigint generated by default as identity primary key, titulo text not null, data_escala date, status text, observacoes text, funcoes_usuarios jsonb, tonalidades_musicas jsonb);
    create table escala_usuarios(escala_id bigint references escalas(id) on delete cascade, usuario_id uuid references profiles(id), primary key(escala_id, usuario_id));
    create table escala_musicas(escala_id bigint references escalas(id) on delete cascade, musica_id bigint references musicas(id), primary key(escala_id, musica_id));
    insert into profiles values ('${user}'), ('${other}');`);
  await db.exec(readFileSync("scripts/configurar-notificacoes-supabase.sql", "utf8"));
  await db.exec(`insert into push_subscriptions(id,usuario_id,endpoint,p256dh,auth) values ('${device}','${user}','https://fcm.googleapis.com/test','public','private');`);
}, 30000);
afterAll(async () => { await db?.close(); });
describe("transação PostgreSQL de escala e notificações", () => {
  it("persiste vínculos, aviso e fila juntos", async () => {
    const result = await save("criar", null, null, state, [notice]);
    expect(result.rows[0].id).toBeGreaterThan(0);
    expect((await db.query("select * from escala_usuarios")).rows).toHaveLength(1);
    expect((await db.query("select * from notifications")).rows).toHaveLength(1);
    expect((await db.query("select * from push_deliveries")).rows).toHaveLength(1);
  });
  it("reverte a escala se a persistência do aviso falhar", async () => {
    await expect(save("criar", null, null, state, [{ ...notice, usuario_id: device }])).rejects.toThrow();
    expect((await db.query("select * from escalas")).rows).toHaveLength(1);
  });
  it("detecta edição concorrente sem sobrescrever nem duplicar avisos", async () => {
    const id = (await db.query<{ id: number }>("select id from escalas")).rows[0].id;
    await save("editar", id, state, { ...state, titulo: "Atualizado" }, [{ ...notice, tipo: "alteracao" }]);
    await expect(save("editar", id, state, { ...state, titulo: "Obsoleto" }, [notice])).rejects.toThrow("WF_CONFLICT");
    expect((await db.query<{ titulo: string }>("select titulo from escalas")).rows[0].titulo).toBe("Atualizado");
    expect((await db.query("select * from notifications")).rows).toHaveLength(2);
  });
  it("não entrega o mesmo lote para dois trabalhadores", async () => {
    expect((await db.query("select * from wf_claim_push()")).rows).toHaveLength(2);
    expect((await db.query("select * from wf_claim_push()")).rows).toHaveLength(0);
  });
  it("bloqueia acesso direto de usuários a avisos e endpoints privados", async () => {
    await db.exec("set role authenticated");
    try {
      await expect(db.query("select * from notifications")).rejects.toThrow("permission denied");
      await expect(db.query("select * from push_subscriptions")).rejects.toThrow("permission denied");
      await expect(db.query("select * from wf_claim_push()")).rejects.toThrow("permission denied");
      await expect(save("criar", null, null, state, [notice])).rejects.toThrow("permission denied");
    } finally { await db.exec("reset role"); }
  });
});
